# Generated by Django 2.0.3 on 2018-03-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='serverFiles')),
            ],
        ),
        migrations.CreateModel(
            name='Recording_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=5)),
                ('audio_file', models.FileField(upload_to='')),
                ('translate_lang', models.CharField(max_length=5)),
                ('transcript_lang', models.CharField(max_length=5)),
                ('session_key', models.CharField(max_length=100)),
                ('extension', models.CharField(max_length=5)),
            ],
        ),
    ]
